### ISSUE TITLE
Señal reset o clear

### ISSUE THREAD

**Issue by masoto22** [IIC2343/Syllabus-2024-1#11]
Hola! Escribo porque me surgió una duda con el enunciado de la tarea. Dice en la descripción: "Similar a como se construye un Adder a partir de varios Full Adders conectados en paralelo, un registro se construye conectando flip-flops paralelamente. Además, se agregan las señales load y reset" y luego nuevamente se menciona la señal reset, pero en las tareas por hacer dice: "El registro, al ser completado, debe ser capaz de cargar los datos si la señal load está activada y reiniciar el valor a 0 al tener la señal clear activada."

La señal clear hace referencia a la señal reset antes mencionada o es otra?

Gracias

**Comment by R0W5tortion** [comment]
Efectivamente, cuando decimos señal clear o reset estamos hablando de lo mismo

Perdón por la confusión

Saludos

**Comment by masoto22** [comment]
Ok, muchas gracias!! 

Saludos
