### ISSUE TITLE
Flips Flops D Para la Actividad

### ISSUE THREAD

**Issue by FranciscoLabra125** [IIC2343/Syllabus-2024-1#14]
Me gustaria saber si, se que el elemento C definido en el FFD es esencial para que funcione como tal, pero tiene algun uso cuando lo utilizamos de componente al elemento en el que lo estamos llamando?

**Comment by octavioaguila** [comment]
Misma duda!

**Comment by R0W5tortion** [comment]
Esa es la señal del clock. Para que un registro no cause comportamientos inesperados es necesario que los registros solo almacenen información durante algún flanco del clock (en nuestro caso, el de subida).
