### ISSUE TITLE
Tarea laboratorio

### ISSUE THREAD

**Issue by domenicahoppe** [IIC2343/Syllabus-2024-1#15]
Hola! Para la tarea del laboratorio podemos usar la función rising_edge()? Y es necesario crear un FFD como componente (e instancia) en el archivo Reg??

**Comment by R0W5tortion** [comment]
No pueden usar rising_edge() en ninguno de los dos archivos que tienen que entregar (Reg y PC). El componente FFD ya está en el código base que les pasamos, solo hay que instanciarlo
