### ISSUE TITLE
Etapa 1: Dudas sobre PC

### ISSUE THREAD

**Issue by cron53** [IIC2343/Syllabus-2024-1#18]
Hola, tengo 2 dudas sobre el Program Counter:
1. El enunciado dice "_Un registro contador PC para el address de la instrucción del programa, de al menos 12 bits._". Como los registros son de 16, y ya tienen implementado up y down, ¿puede ser el PC de 16 bits también?
2. Por el diagrama no me queda tan claro de donde se carga la información. De la ROM o de la RAM? Esto sería **Ins** de la tabla de assebler

**Comment by Javipipi** [comment]
Hola
1. Sí puedes hacer el PC de 16 bits, pero de ahí tienen que salir 12 bits porque no le puedes traspasar 16 bits de adress a la ROM, así que dentro del PC puede ser de 16 bits pero tendrías que eliminar 4 al salir.
2. Las instrucciones se cargan en la ROM, la RAM se encarga de lo relacionado a la memoria.
