### ISSUE TITLE
[Actividad RISC-V] Tests

### ISSUE THREAD

**Issue by MarioErnst** [IIC2343/Syllabus-2024-1#41]
Hola, no entiendo como funcionan los tests, porque son para cada subrutina por separado por lo que entiendo, pero si solo me dan el start_ y el flujo normal usa todas las subrutinas a implementar, sin todas las otras no puedo probar una individualmente porque no me corre el codigo, o como puedo probar una sola subrutina con esos tests?.

**Comment by Geeermy** [comment]
Por favor, **usar _label_ solicitado**.

Contestaremos tu duda en breve.
