### ISSUE TITLE
[Actividad RISK-V] 3.Experiencia

### ISSUE THREAD

**Issue by domiluders** [IIC2343/Syllabus-2024-1#42]
Hola!

Tengo una duda en la parte 3, la de experiencia. 
El enunciado dice: 
"3. Si la experiencia total es menor a 100, se debe retornar.
4. Si la experiencia total es mayor o igual a 100, se debe subir de nivel. Antes de hacerlo, debe guardar como experiencia la resta entre el valor computado y 100."

Entonces si la experiencia sube por ejemplo de 10 a 30 no debo guardarla?

**Comment by sufigueroa** [comment]
Holaa!! Si se debe guardar, pero no se debe realizar la resta.
