### ISSUE TITLE
Actividad RISC-V 4. Evolución

### ISSUE THREAD

**Issue by MartinCastillo** [IIC2343/Syllabus-2024-1#43]
Hola en la parte 4 de la subrrutina evolve al buscar entre los valores de la lista evolutions se puede crear una variable nueva en memoria que indique la cantidad de tripletas en evolutions? O se puede asumir un largo como el que está en el código base?

**Comment by sufigueroa** [comment]
Hola!! Si puedes agregarlo, pero no se van a agregar nuevas tripletas. También puedes considerar que siempre estarán ordenadas de manera creciente según el primer elemento :)
