### ISSUE TITLE
[Actividad RISC-V] 1. attack

### ISSUE THREAD

**Issue by masoto22** [IIC2343/Syllabus-2024-1#44]
Hola! Quería hacer una consulta respecto a la subrutina _critical_damage, en el enunciado indica que si el daño es crítico se suma 4 al ataque del pokemon. Por lo que entendí viendo el código, en _critical_damage como tal no se hace la suma verdad? Solo se indica 1 si el daño es crítico o 0 si no. Esto sería así? Gracias

**Comment by kipasten** [comment]
Cómo indicas, _critical_damage imprime si es que el pokemon hace daño crítico y retorna 0 o 1 en el registro a0, tu debes sumar 4 al daño que hara el ataque si es 1 y no hacer nada en otro caso.
