### ISSUE TITLE
[Actividad RISC-V] Duda uso de lw

### ISSUE THREAD

**Issue by masoto22** [IIC2343/Syllabus-2024-1#45]
Hola de nuevo :)

Me surgió la siguiente duda:
- Si  hago por ejemplo sw rd, 4(sp)
- Luego llamo a un subrutina que cambia el valor de rd, entonces después de ella debo ocupar lw rd, 4(sp) para recuperar el valor, pero no restauro el stack
- Llamo a otra subrutina y nuevamente hago lw rd, 4(sp), ¿va a seguir el mismo valor en 4(sp) si no restauré el stack? ¿Es mala práctica si no lo hago? (donde volveré a usar el valor de rd respaldado, no restauré el stack pero me surgió la duda si se mantiene o no el valor efectivamente)

Gracias

**Comment by sufigueroa** [comment]
Holaa!! Si se puede hacer eso, seria correcto :)

**Comment by masoto22** [comment]
genial, gracias!
