### ISSUE TITLE
Actividad RISC-V Comportamiento esperado flujo completo

### ISSUE THREAD

**Issue by MartinCastillo** [IIC2343/Syllabus-2024-1#48]
Hola! Cual es la salida esperada del programa completo con el .data que viene en el código base? Para comprobar si la solución es correcta

**Comment by Geeermy** [comment]
¡Hola!

Nunca habrá una salida concreta dado que las pruebas están aleatorizadas (por ejemplo, el ataque crítico, el envenenamiento y el dormir). De momento:

* Verifica que pasen los tests individuales.
* Prueba la simulación completa y verifica que:  uno de los Pokémon haya llegado al nivel 40; y que su ID sea consistente con el nivel (i.e. que haya evolucionado correspondientemente).

Si aún así quedas con dudas del funcionamiento, te invito a escribirnos un correo para ver tu caso puntual.

¡Saludos!
