### ISSUE TITLE
añadir tripleta a .evolutions

### ISSUE THREAD

**Issue by wintermelyn** [IIC2343/Syllabus-2024-1#49]
Me surgió esta duda de la [issue 43](https://github.com/IIC2343/Syllabus-2024-1/issues/43)
Se puede añadir una ultima tripleta que muestre el final de la lista de evoluciones?

```
evolutions: 
  .word	  1, 2, 16	# (Bulbasaur, Ivysaur, nivel 16)
	  2, 3, 32	# (Ivysaur, Venusaur, nivel 32)
	  4, 5, 16	# (Charmander, Charmeleon, nivel 16)
	  5, 6, 36 	# (Charmeleon, Charizard, nivel 36)
	  7, 8, 16	# (Squirtle, Wartortle, nivel 16)
	  8, 9, 36	# (Wartortle, Blastoise, nivel 36)
	  0, 0, 0       # Fin de la lista de evoluciones
```

**Comment by Geeermy** [comment]
¡Hola!

Vuelvo a abrir la issue para que todos sepan: La lista de tripletas **no cambiará**. No es necesario que manejen la forma de determinar que se acabaron. Asume que siempre existirán solo 6 elementos.

¡Saludos!
