### ISSUE TITLE
retorno si el pokemon está dormido

### ISSUE THREAD

**Issue by pgaguilera** [IIC2343/Syllabus-2024-1#50]
Hola! en attack dice que si el pokemon está dormido se debe retornar la función ¿Para hacer ese retorno se debe ocupar la instrucción que venía escrita por defecto en cada subrutina ?  jalr zero, 0(ra)

**Comment by sufigueroa** [comment]
Hola!! Puedes usar esa instrucción para retornar, o cualquier otra que realice el mismo objetivo :)
