### ISSUE TITLE
error con _type_boost

### ISSUE THREAD

**Issue by dalcalde5150** [IIC2343/Syllabus-2024-1#53]
Cuando hago en attack: 
jal ra, _type_boost
lw t0,0(a0)

Me arroja el error:
Runtime exception at 0x004005c8: Load address not aligned to word boundary 0xfffffffd

Segun internet es que la cantidad de bytes de retorno no calzan, como puedo arreglar esto o que estoy haciendo mal?

**Comment by Geeermy** [comment]
¡Hola!

1. Trata de no compartir líneas de código, por favor.
2. Cuando llamas a _type_boost, te entrega un valor numérico y sobreescribe el contenido original del registro a0. El error ocurre porque tratas de usar a0 como una dirección de memoria, cuando posterior a la ejecución de _type_boost deja de serlo. Debes modificar tu código para usar este valor correctamente y no perder el valor original de a0, asumiendo que requieres usarlo después.


¡Saludos!
