### ISSUE TITLE
[Actividad RISC-V] Error print_pokemon

### ISSUE THREAD

**Issue by vicentesalazar** [IIC2343/Syllabus-2024-1#58]
Hola, al correr distintos test tengo errores con la impresión en consola, por ejemplo al correr un test de peleaa, obtengo el siguiente output: 
Bulbasaur:  
ID: 1
Tipo: 0
Nivel: 5
EXP: 0
Estado: 0
HP: 21
HP Total: 21
Ataque: 11
Defensa: 8
Ataque Especial: 13
Defensa Especial: 13
Velocidad: 11
ID: 20
Tipo: 1
Nivel: 5
EXP: 0
Estado: 0
HP: 20
HP Total: 20
Ataque: 12
Defensa: 7
Ataque Especial: 10
Defensa Especial: 11
Velocidad: 13
Por alguna razon no se está imprimiendo todaa la información del segundo pokemon

**Comment by sufigueroa** [comment]
Hola! Noto que para el segundo pokemon no se imprime su nombre y se esta imprimiendo mal su ID. No imprime el nombre dado que busca el nombre con ID 20 y no existe. Probablemente dentro de la subrutina que llamas estes editando la variable ID de manera incorrecta. Pero sin mas contexto no puedo saber si el error es este o otro.
