### ISSUE TITLE
[Actividad RISC-V] Bonus -6

### ISSUE THREAD

**Issue by domiluders** [IIC2343/Syllabus-2024-1#60]
Hola!

Tengo una duda en la ultima parte. 

El enunciado dice: 
"2.Llamar a la subrutina _rand_number. Esta recibe como argumento un número a través del registro a0 , y retorna un valor en el rango [0,a0 [. Por ejemplo, si a0 = 10, entonces retorna un número entre 0 y 9. El valor retornado se almacena en el registro a0 .
3. Dado el número generado, se decide con un 50 % de probabilidad si el Pokémon despierta o no. Si sigue dormido, hay que retornar."

No entiendo a de que me sirve el número generado y como se conecta con ese 50% de probabilidad.

Saludossss

**Comment by Geeermy** [comment]
¡Hola!

La idea es que lo uses para generar la obtención aleatoria de un número y, en base a ese resultado, que modeles un 50% de probabilidad de que ocurra el evento o no. Se puede usar de muchas formas y la idea es que tú determines la que te haga más sentido. No te podemos decir exactamente cómo usarla, lamentablemente.

¡Saludos!
