### ISSUE TITLE
[Actividad RISC-V] Se pasan todos los tests pero la simulación con _combate tira errores

### ISSUE THREAD

**Issue by anibalriveros** [IIC2343/Syllabus-2024-1#61]
Holaa,

Me pasa que ya paso todos los tests y obtengo el resultado esperado, pero al momento de correr la simulacion completa, me aparece un error en una línea nada que ver con las subrutinas que yo implemente. ¿Qué sucede en ese caso?

**Comment by sufigueroa** [comment]
Hola!! Que error aparece?

**Comment by anibalriveros** [comment]
Go: execution terminated with errors.
line 448: Runtime exception at 0x004004a0: Cannot read directly from text segment!0x0040058c

**Comment by andrius6789** [comment]
uhhhhhh, me pasa exactamente lo mismo. Por separado funcionan pero al momento de correr todo obtengo ese error en mi caso con la linea:
lw t6, 32(a1) #busca cargar la defensa

y eso que antes esta la linea que carga el ataque y esa no falla. No termino de entender que problema tengo y he estado muuucho rato intentando solucionarlo 😅

**Comment by sufigueroa** [comment]
Hola!! Es probable que no estes devolviendo el stack a su estado original antes de cada retorno. Es posible que al retornar el sp este en otra posicion y por eso al cargar el valor de a1 que se encontraba en el stack, se guarda un valor incorrecto y da ese error.
