### ISSUE TITLE
Bucle combate

### ISSUE THREAD

**Issue by carlosiskindacool** [IIC2343/Syllabus-2024-1#63]
Holaa, qué pasa si me corren todos los tests pero al correr el programa completo queda en un bucle infinito? Significa que en vd no está correcto el código o es esperable?

**Comment by Geeermy** [comment]
¡Hola!

¿Cómo sabes que se queda en un bucle infinito?

A modo de sugerencia, agrega las siguientes instrucciones en `_end`:

```
li a7, 10
ecall
```

Así gatillas el cierre del proceso. Si ahí sale bien, entonces no es que hayas estado en un bucle infinito, sino que solo faltaba cortar el programa.

Quedo atento.

**Comment by Geeermy** [comment]
PD: Recuerda poner el título en la _issue_ para que aparezca el _label_. Gracias.

**Comment by Geeermy** [comment]
¡Hola de nuevo!

Acabo de caer en cuenta de algo: ¿implementaste los bonus?

Si no los implementas, entonces existe la probabilidad de que tus Pokémon se duerman. Si no implementas la subrutina `wake_up`, entonces nunca despertarán y, por ende, nunca terminarán una batalla. Esto implica que no subirán de nivel y por eso se genera el bucle. Por lo tanto... el bucle es **esperable**.

**Comment by carlosiskindacool** [comment]
Ahh entiendo. Efectivamente, no implementé los bonus y deducía que se podía deber a que los pokemones se pusieran a dormir. Muchas gracias:)
