### ISSUE TITLE
Errores, uno con el test 8, y otro con el código original al correr el programa entero...

### ISSUE THREAD

**Issue by based-on-what** [IIC2343/Syllabus-2024-1#64]
Hola a todos, al correr el test 8 me da este mensaje de error, me es imposible saber dónde podría estar el problema de esta forma:
![imagen](https://github.com/IIC2343/Syllabus-2024-1/assets/62000495/b6468ced-1075-410e-8c74-06020e28786e)
Por otra parte, cuando corro el programa que se entrega, obtengo este resultado:
![imagen](https://github.com/IIC2343/Syllabus-2024-1/assets/62000495/4357742b-e7aa-4734-b8dd-96fc4eb8c63e)
Cabe destacar que con los demás tests tengo los resultados indicados, entonces me achaca bastante que el entregable me de errores que están en el **código original de la tarea**

Saludos, ¿qué se puede hacer en este caso?

**Comment by Geeermy** [comment]
Hola Ignacio.

1. Por favor, sigue las instrucciones del enunciado y añade en el título "Actividad - RISC-V" para que se le asocie a tu _issue_ el _label_ correcto.
2. RARS, por defecto, te permite identificar la línea que se cae en tu código. Si buscas el ícono que corresponde a una flecha que apunta a la izquierda y contiene un 1, puedes empezar a retroceder un ciclo hasta que te muestre exactamente la última instrucción que ejecutó. Con esto puedes detectarla y hacer cambios al respecto.
3. Los errores apuntan a un posible error de lectura de memoria, por lo que el error _podría_ estar relacionado al uso de registros como dirección de memoria inválidas (lo que pasa, por ejemplo, cuando no respaldas estos valores antes de la ejecución de subrutinas que vienen dadas).

Tiene sentido que tu código final no corra si existe al menos un _test_ que falla. En ese sentido, prioriza arreglar el _test_ primero ya que es, probablemente, la fuente de error del flujo completo. Recuerda que igual revisaremos las subrutinas por separado.

¡Saludos!

**Comment by based-on-what** [comment]
> Hola Ignacio.
> 
>     2. RARS, por defecto, te permite identificar la línea que se cae en tu código. Si buscas el ícono que corresponde a una flecha que apunta a la izquierda y contiene un 1, puedes empezar a retroceder un ciclo hasta que te muestre exactamente la última instrucción que ejecutó. Con esto puedes detectarla y hacer cambios al respecto.
> 
Hice eso, la última línea ejecutada fue la que imprime el mensaje de felicitaciones por subir de nivel, pero honestamente no logro ver el error que sigue después :(

>     3. Los errores apuntan a un posible error de lectura de memoria, por lo que el error _podría_ estar relacionado al uso de registros como dirección de memoria inválidas (lo que pasa, por ejemplo, cuando no respaldas estos valores antes de la ejecución de subrutinas que vienen dadas).

Los valores a1 y a0 los respaldo en valores temporales tipo s*, y después restauro los valores correspondientes a a0 y a1
> 
> Tiene sentido que tu código final no corra si existe al menos un _test_ que falla. En ese sentido, prioriza arreglar el _test_ primero ya que es, probablemente, la fuente de error del flujo completo. Recuerda que igual revisaremos las subrutinas por separado.
> 
> ¡Saludos!

**Comment by Geeermy** [comment]
¿Verificaste que en las subrutinas que llamas **no se usen** esos registros `s*` mencionados? Porque si es el caso, entonces ahí podrías estar generando inconsistencias. Te sugiero que respaldes valores usando el _stack_, no otros registros (que es lo que dictamina la convención).

¡Saludos!

**Comment by based-on-what** [comment]
> ¿Verificaste que en las subrutinas que llamas **no se usen** esos registros `s*` mencionados? Porque si es el caso, entonces ahí podrías estar generando inconsistencias. Te sugiero que respaldes valores usando el _stack_, no otros registros (que es lo que dictamina la convención).
> 
> ¡Saludos!

Así tengo el bloque de _type_boost:
![imagen](https://github.com/IIC2343/Syllabus-2024-1/assets/62000495/8004bee3-0a4d-4b0e-8464-2c835aa12b23)

**Comment by Geeermy** [comment]
Ignacio, está **absolutamente prohibido** que compartas capturas de pantalla de tu código. Otros/as estudiantes pueden basarse en él para realizar su actividad. Esto no solo aplica aquí, sino que en cualquier canal. Las sanciones son equivalentes a las de copia.

Borré tu comentario, pero dejo la advertencia.

Si te ves en la necesidad de compartir código, escríbeme un correo.

**Comment by based-on-what** [comment]
> Ignacio, está **absolutamente prohibido** que compartas capturas de pantalla de tu código. Otros/as estudiantes pueden basarse en él para realizar su actividad. Esto no solo aplica aquí, sino que en cualquier canal. Las sanciones son equivalentes a las de copia.
> 
> Borré tu comentario, pero dejo la advertencia.
> 
> Si te ves en la necesidad de compartir código, escríbeme un correo.

De acuerdo profesor, le envié un correo

**Comment by sufigueroa** [comment]
Hola! Probablemente el error es lo que menciono en la issue #61
