### ISSUE TITLE
Error cargando velocidad pokemon en Turn_attack

### ISSUE THREAD

**Issue by ctoro05** [IIC2343/Syllabus-2024-1#65]
Hola! Al comienzo de mi programa, al cargar las velocidades de los pokemones en turn attack estoy teniendo un problema por:

Error in C:\Users\ctoro\OneDrive\Escritorio\p4_4 arqui\pokemon-N-Alumno.asm line 630: Runtime exception at 0x00400688: Load address not aligned to word boundary 0x10010063

Step: execution terminated with errors.

Literalmente es el comienzo del código, entonces si guardo espacios de memoria no entiendo por qué tendría ese error

**Comment by ctoro05** [comment]
attack si me funciona, turn attack no

**Comment by sufigueroa** [comment]
Hola!! Este error ha sido explicado en varias issues. Tiene que ver con el respaldo de los registros a0 y a1.
